

// Generated by https://quicktype.io

export interface LikeResponse {
    ok:    boolean;
    total: number;
    likes: Like[];
}

export interface Like {
    ficha: string;
    user:  User;
    id:    string;
}

export interface Ficha {
    _id:         string;
    title:       string;
    author:      string;
    fecha_pub:   string;
    description: string;
    image:       string;
    likes:       number;
    user:        string;
    __v:         number;
}

export interface User {
    _id:     string;
    name:    string;
    surname: string;
}
